# Generated by Django 5.2.16 on 2026-07-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconnection',
            name='app_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopconnection',
            name='app_installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
