# Generated by Django 5.2

from django.db import migrations, models


def _dedupe_shops(apps, schema_editor):
    """Keep one ShopConnection per shop domain before adding unique constraint."""
    ShopConnection = apps.get_model("dashboard", "ShopConnection")
    seen = set()
    # Prefer active (app_installed) rows, then newest.
    qs = ShopConnection.objects.order_by("-app_installed", "-installed_at", "-id")
    for row in qs:
        if row.shop in seen:
            row.delete()
        else:
            seen.add(row.shop)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_activityevent_userplan"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shopconnection",
            unique_together=set(),
        ),
        migrations.RunPython(_dedupe_shops, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="shopconnection",
            name="shop",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
