"""
apps/dashboard/migrations/0005_settings_prefs_and_plan_renews.py — Django migration: 0005_settings_prefs_and_plan_renews.
"""

# Generated by Django 5.2.16 on 2026-07-12 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_shopconnection_shop_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='renews_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_build_success', models.BooleanField(default=True)),
                ('email_build_failed', models.BooleanField(default=True)),
                ('email_winning_products', models.BooleanField(default=True)),
                ('email_tips', models.BooleanField(default=False)),
                ('default_niche_slug', models.SlugField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
