"""
apps/dashboard/migrations/0006_shop_product_count_cache.py — Django migration: 0006_shop_product_count_cache.
"""

# Generated by Django 5.2.16 on 2026-07-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_settings_prefs_and_plan_renews'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconnection',
            name='store_product_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopconnection',
            name='store_product_count_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
