"""
apps/builder/migrations/0002_buildjob_product_count_buildjob_progress_step_and_more.py — Django migration: 0002_buildjob_product_count_buildjob_progress_step_and_more.
"""

# Generated by Django 5.2.16 on 2026-07-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildjob',
            name='product_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildjob',
            name='progress_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildjob',
            name='store_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='nichepack',
            name='product_count',
            field=models.PositiveIntegerField(default=48),
        ),
    ]
