# Generated by Django 5.2.16 on 2026-07-12 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_buildjob_product_count_buildjob_progress_step_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nichepack',
            options={'ordering': ['sort_order', 'codename', 'name']},
        ),
        migrations.AddField(
            model_name='buildjob',
            name='selected_product_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='buildjob',
            name='skip_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nichepack',
            name='accent',
            field=models.CharField(default='#4edea3', max_length=16),
        ),
        migrations.AddField(
            model_name='nichepack',
            name='codename',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='nichepack',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nichepack',
            name='theme_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='nichepack',
            name='product_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WinningProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accent', models.CharField(default='#4edea3', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('niche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='builder.nichepack')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
