"""
apps/builder/migrations/0004_buildjob_zentra_build_id.py — Django migration: 0004_buildjob_zentra_build_id.
"""

# Generated by Django 5.2.16 on 2026-07-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_niche_products_builder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildjob',
            name='engine_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buildjob',
            name='live_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='buildjob',
            name='zentra_build_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
