# Generated by Django 5.2.16 on 2026-07-13 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(help_text='Stable id (hash of product URL). Prefer this over sheet-N.', max_length=64, unique=True)),
                ('product_key', models.CharField(db_index=True, help_text='Normalized domain::handle for dedup', max_length=512, unique=True)),
                ('ad_id', models.CharField(blank=True, default='', max_length=128)),
                ('page_name', models.CharField(blank=True, default='', max_length=255)),
                ('landing_url', models.URLField(blank=True, default='', max_length=1000)),
                ('product_url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('price', models.CharField(blank=True, default='', max_length=64)),
                ('compare_price', models.CharField(blank=True, default='', max_length=64)),
                ('ratings', models.CharField(blank=True, default='', max_length=32)),
                ('review_count', models.CharField(blank=True, default='', max_length=32)),
                ('product_images', models.TextField(blank=True, default='')),
                ('feature_image', models.URLField(blank=True, default='', max_length=1000)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('archived', models.BooleanField(default=False)),
                ('sheet_row', models.PositiveIntegerField(blank=True, help_text='Last known 1-based sheet data row (fragile; for sync only)', null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catalog product',
                'verbose_name_plural': 'Catalog products',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('mode', models.CharField(choices=[('single', 'Single query'), ('all_niches', 'All niches'), ('sync_sheet', 'Sync from sheet'), ('clean_dupes', 'Clean sheet duplicates')], default='single', max_length=16)),
                ('query', models.CharField(blank=True, default='fashion', max_length=255)),
                ('country', models.CharField(blank=True, default='US', max_length=8)),
                ('target_rows', models.PositiveIntegerField(default=50)),
                ('products_per_store', models.PositiveIntegerField(default=10)),
                ('sheet_tab', models.CharField(blank=True, default='', max_length=128)),
                ('rows_written', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scrape run',
                'verbose_name_plural': 'Scrape runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
