"""
apps/catalog/migrations/0002_shop_import.py — Django migration: 0002_shop_import.
"""

# Generated by Django 5.2.16 on 2026-07-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogproduct',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Winning Product Vault', 'verbose_name_plural': 'Winning Product Vault'},
        ),
        migrations.AlterModelOptions(
            name='scraperun',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Hunter', 'verbose_name_plural': 'Product Hunter'},
        ),
        migrations.AlterField(
            model_name='scraperun',
            name='mode',
            field=models.CharField(choices=[('single', 'Single query'), ('all_niches', 'All niches'), ('sync_sheet', 'Sync from sheet'), ('clean_dupes', 'Clean sheet duplicates'), ('fill_ids', 'Fill stable ids on sheet')], default='single', max_length=16),
        ),
        migrations.CreateModel(
            name='ShopImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(db_index=True, max_length=255)),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('cost', models.CharField(blank=True, default='10', max_length=64)),
                ('sell_price', models.CharField(blank=True, default='', max_length=64)),
                ('compare_at_price', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('product_url', models.URLField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('in_store', 'In store'), ('removed_from_store', 'Removed from store')], db_index=True, default='imported', max_length=32)),
                ('shopify_product_id', models.CharField(blank=True, default='', max_length=128)),
                ('node_import_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'My Import',
                'verbose_name_plural': 'My Imports',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'source_id'), name='uniq_shop_import_source')],
            },
        ),
    ]
